vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        projects:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        skills:
            uri_prefix: /images/skills
            upload_destination: '%kernel.project_dir%/public/images/skills'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        mycv:
            uri_prefix: /cv
            upload_destination: '%kernel.project_dir%/public/cv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        user:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
